### ISSUE TITLE
Can't Trade with Myself in Gen 1 Pokemon

### ISSUE THREAD

**Issue by Myusicman** [visualboyadvance-m/website#1]
Hello!  I am fairly new to using emulators.  I noticed that you can open multiple screens up for the emulator and set up a link to access multiplayer and trade.  However, it seems like the games do not register the fact that the link is active.

Can you show me a step-by-step process on how to get the link active so I can trade my Pokemon via cable link and complete my Pokedex?  Thank you for your time.

**Comment by ZachBacon** [comment]
Post your issue here https://github.com/visualboyadvance-m/visualboyadvance-m/issues This is specific to the website/forum performance issue, not the emulator.

**Comment by Zack583** [comment]
I always found problems to do things like that on this emulator to PC, but always manage to do it on the Android version, I didn't check the newest version to PC but still...
